notifications:
  email: false

language: go

go:
  - 1.7
  - 1.8
  - 1.9

before_install:
  - go get -v github.com/golang/lint/golint
  - go get ./...

script:
  - golint ./...
  - go vet ./...
  - go test -v ./...
